export const EDIT_QUANTITY_PRODUCT = 'EDIT_QUANTITY_PRODUCT';
export const EDIT_QUANTITY_PRODUCT_SUCCESS = 'EDIT_QUANTITY_PRODUCT_SUCCESS';
export const EDIT_QUANTITY_PRODUCT_FAIL = 'EDIT_QUANTITY_PRODUCT_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';


export const LOADING_DATA = 'LOADING_DATA';

export const ADD_CART = 'ADD_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';

export const LOGIN = 'LOGIN';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_MODAL_ADD = 'SHOW_MODAL_ADD';
export const HIDE_MODAL_ADD = 'HIDE_MODAL_ADD';

export const GET_DATA_PRODUCT = 'GET_DATA_PRODUCT';
export const GET_DATA_PRODUCT_SUCCESS = 'GET_DATA_PRODUCT_SUCCESS';
export const GET_DATA_PRODUCT_FAIL = 'GET_DATA_PRODUCT_FAIL';