export const EDIT_QUANTITY_PRODUCT = 'EDIT_QUANTITY_PRODUCT';
export const EDIT_QUANTITY_PRODUCT_SUCCESS = 'EDIT_QUANTITY_PRODUCT_SUCCESS';
export const EDIT_QUANTITY_PRODUCT_FAIL = 'EDIT_QUANTITY_PRODUCT_FAIL';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';


export const LOADING_DATA = 'LOADING_DATA';

export const ADD_CART = 'ADD_CART';
export const ADD_CART_SUCCESS = 'ADD_CART_SUCCESS';
export const ADD_CART_FAIL = 'ADD_CART_FAIL';
